[cerebrium.deployment]
name = "image-classifier"
python_version = "3.10"
docker_base_image_url = ""  
include = ["*/**"]         

[cerebrium.hardware]
cpu = 1
memory = 4.0
compute = "L40s"            

[cerebrium.scaling]
min_replicas = 0
max_replicas = 2
cooldown = 30

[cerebrium.dependencies.pip]

